/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BudgetAllocation {
    savingPct: number;
    investingPct: number;
    spendingPct: number;
}
export interface IncomeSource {
    name: string;
    amount: number;
}
export interface DigitalLocker {
    unlockDate?: bigint;
    locked: boolean;
    conditionType?: UnlockCondition;
}
export interface Profile {
    expenses: Array<Expense>;
    digitalLocker: DigitalLocker;
    userProfile: UserProfile;
    allocation: BudgetAllocation;
    savingsGoals: Array<SavingsGoal>;
    incomeSources: Array<IncomeSource>;
}
export interface Expense {
    date: bigint;
    note: string;
    category: string;
    amount: number;
}
export type UnlockCondition = {
    __kind__: "goalMet";
    goalMet: bigint;
} | {
    __kind__: "timePeriod";
    timePeriod: bigint;
};
export interface UserProfile {
    displayName: string;
}
export interface SavingsGoal {
    name: string;
    locked: boolean;
    deadline: bigint;
    targetAmount: number;
    currentAmount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExpense(amount: number, category: string, note: string): Promise<void>;
    addIncome(name: string, amount: number): Promise<void>;
    addSavingsGoal(name: string, target: number, deadline: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpenses(): Promise<Array<Expense>>;
    getInvestmentSuggestions(): Promise<Array<[string, number]>>;
    getLockerStatus(): Promise<DigitalLocker>;
    getProfile(user: Principal): Promise<Profile>;
    getSavingsGoals(): Promise<Array<SavingsGoal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    requestUnlock(conditionType: string, goalIndex: bigint | null, periodDays: bigint | null): Promise<boolean>;
    saveCallerUserProfile(up: UserProfile): Promise<void>;
    setAllocationSplit(spending: number, saving: number, investing: number): Promise<void>;
    updateSavingsGoal(index: bigint, amount: number): Promise<void>;
}
import type { BudgetAllocation as _BudgetAllocation, DigitalLocker as _DigitalLocker, Expense as _Expense, IncomeSource as _IncomeSource, Profile as _Profile, SavingsGoal as _SavingsGoal, UnlockCondition as _UnlockCondition, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExpense(arg0: number, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2);
            return result;
        }
    }
    async addIncome(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncome(arg0, arg1);
            return result;
        }
    }
    async addSavingsGoal(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSavingsGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSavingsGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getInvestmentSuggestions(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentSuggestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentSuggestions();
            return result;
        }
    }
    async getLockerStatus(): Promise<DigitalLocker> {
        if (this.processError) {
            try {
                const result = await this.actor.getLockerStatus();
                return from_candid_DigitalLocker_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLockerStatus();
            return from_candid_DigitalLocker_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_Profile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_Profile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavingsGoals(): Promise<Array<SavingsGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsGoals();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestUnlock(arg0: string, arg1: bigint | null, arg2: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.requestUnlock(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestUnlock(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAllocationSplit(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllocationSplit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllocationSplit(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSavingsGoal(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSavingsGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSavingsGoal(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DigitalLocker_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DigitalLocker): DigitalLocker {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UnlockCondition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnlockCondition): UnlockCondition {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UnlockCondition]): UnlockCondition | null {
    return value.length === 0 ? null : from_candid_UnlockCondition_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expenses: Array<_Expense>;
    digitalLocker: _DigitalLocker;
    userProfile: _UserProfile;
    allocation: _BudgetAllocation;
    savingsGoals: Array<_SavingsGoal>;
    incomeSources: Array<_IncomeSource>;
}): {
    expenses: Array<Expense>;
    digitalLocker: DigitalLocker;
    userProfile: UserProfile;
    allocation: BudgetAllocation;
    savingsGoals: Array<SavingsGoal>;
    incomeSources: Array<IncomeSource>;
} {
    return {
        expenses: value.expenses,
        digitalLocker: from_candid_DigitalLocker_n6(_uploadFile, _downloadFile, value.digitalLocker),
        userProfile: value.userProfile,
        allocation: value.allocation,
        savingsGoals: value.savingsGoals,
        incomeSources: value.incomeSources
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlockDate: [] | [bigint];
    locked: boolean;
    conditionType: [] | [_UnlockCondition];
}): {
    unlockDate?: bigint;
    locked: boolean;
    conditionType?: UnlockCondition;
} {
    return {
        unlockDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.unlockDate)),
        locked: value.locked,
        conditionType: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.conditionType))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalMet: bigint;
} | {
    timePeriod: bigint;
}): {
    __kind__: "goalMet";
    goalMet: bigint;
} | {
    __kind__: "timePeriod";
    timePeriod: bigint;
} {
    return "goalMet" in value ? {
        __kind__: "goalMet",
        goalMet: value.goalMet
    } : "timePeriod" in value ? {
        __kind__: "timePeriod",
        timePeriod: value.timePeriod
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
