/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetAllocation {
  'savingPct' : number,
  'investingPct' : number,
  'spendingPct' : number,
}
export interface DigitalLocker {
  'unlockDate' : [] | [bigint],
  'locked' : boolean,
  'conditionType' : [] | [UnlockCondition],
}
export interface Expense {
  'date' : bigint,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface IncomeSource { 'name' : string, 'amount' : number }
export interface Profile {
  'expenses' : Array<Expense>,
  'digitalLocker' : DigitalLocker,
  'userProfile' : UserProfile,
  'allocation' : BudgetAllocation,
  'savingsGoals' : Array<SavingsGoal>,
  'incomeSources' : Array<IncomeSource>,
}
export interface SavingsGoal {
  'name' : string,
  'locked' : boolean,
  'deadline' : bigint,
  'targetAmount' : number,
  'currentAmount' : number,
}
export type SendFundsError = { 'userNotFound' : null } |
  { 'other' : string } |
  { 'insufficientFunds' : null };
export type UnlockCondition = { 'goalMet' : bigint } |
  { 'timePeriod' : bigint };
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : bigint,
  'transactionType' : string,
  'note' : string,
  'timestamp' : bigint,
  'amount' : number,
  'recipientLabel' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[number, string, string], undefined>,
  'addFundsToWallet' : ActorMethod<[number, [] | [string], string], undefined>,
  'addIncome' : ActorMethod<[string, number], undefined>,
  'addSavingsGoal' : ActorMethod<[string, number, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getInvestmentSuggestions' : ActorMethod<[], Array<[string, number]>>,
  'getLockerStatus' : ActorMethod<[], DigitalLocker>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], number>,
  'getWalletTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestUnlock' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFundsFromWallet' : ActorMethod<
    [string, number, string],
    { 'ok' : WalletTransaction } |
      { 'err' : SendFundsError }
  >,
  'setAllocationSplit' : ActorMethod<[number, number, number], undefined>,
  'transferToLocker' : ActorMethod<[number, string], undefined>,
  'updateSavingsGoal' : ActorMethod<[bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];