/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetAllocation {
  'savingPct' : number,
  'investingPct' : number,
  'spendingPct' : number,
}
export interface DigitalLocker {
  'unlockDate' : [] | [bigint],
  'locked' : boolean,
  'conditionType' : [] | [UnlockCondition],
}
export interface Expense {
  'date' : bigint,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface IncomeSource { 'name' : string, 'amount' : number }
export type KycStatus = { 'full' : null } |
  { 'none' : null } |
  { 'basic' : null };
export interface Profile {
  'expenses' : Array<Expense>,
  'digitalLocker' : DigitalLocker,
  'userProfile' : UserProfile,
  'allocation' : BudgetAllocation,
  'savingsGoals' : Array<SavingsGoal>,
  'incomeSources' : Array<IncomeSource>,
}
export interface SavingsGoal {
  'name' : string,
  'locked' : boolean,
  'deadline' : bigint,
  'targetAmount' : number,
  'currentAmount' : number,
}
export interface SystemStats {
  'fullKycCount' : bigint,
  'totalUsers' : bigint,
  'totalBalance' : bigint,
  'basicKycCount' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'transactionLabel' : string,
  'note' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'lockerTransfer' : null } |
  { 'credit' : null } |
  { 'debit' : null };
export type UnlockCondition = { 'goalMet' : bigint } |
  { 'timePeriod' : bigint };
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletProfile {
  'balance' : bigint,
  'kycStatus' : KycStatus,
  'hasPin' : boolean,
}
export interface WalletSummary {
  'principal' : Principal,
  'balance' : bigint,
  'kycStatus' : KycStatus,
  'transactionCount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[number, string, string], undefined>,
  'addFundsToWallet' : ActorMethod<[bigint, string], undefined>,
  'addIncome' : ActorMethod<[string, number], undefined>,
  'addSavingsGoal' : ActorMethod<[string, number, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWallet' : ActorMethod<[], undefined>,
  'deductFromWallet' : ActorMethod<[bigint, string], undefined>,
  'getAllWalletSummaries' : ActorMethod<
    [],
    [Array<WalletSummary>, SystemStats]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getInvestmentSuggestions' : ActorMethod<[], Array<[string, number]>>,
  'getKYCStatus' : ActorMethod<[], KycStatus>,
  'getLockerStatus' : ActorMethod<[], DigitalLocker>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getWalletProfile' : ActorMethod<[], WalletProfile>,
  'getWalletTransactions' : ActorMethod<[], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestUnlock' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAllocationSplit' : ActorMethod<[number, number, number], undefined>,
  'setWalletPIN' : ActorMethod<[string], undefined>,
  'submitBasicKYC' : ActorMethod<[string, string, string, string], undefined>,
  'submitFullKYC' : ActorMethod<[string, string], undefined>,
  'transferToLockerFromWallet' : ActorMethod<[bigint], undefined>,
  'updateSavingsGoal' : ActorMethod<[bigint, number], undefined>,
  'verifyWalletPIN' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];