/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const KycStatus = IDL.Variant({
  'full' : IDL.Null,
  'none' : IDL.Null,
  'basic' : IDL.Null,
});
export const WalletSummary = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
  'kycStatus' : KycStatus,
  'transactionCount' : IDL.Nat,
});
export const SystemStats = IDL.Record({
  'fullKycCount' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalBalance' : IDL.Nat,
  'basicKycCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const Expense = IDL.Record({
  'date' : IDL.Int,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UnlockCondition = IDL.Variant({
  'goalMet' : IDL.Nat,
  'timePeriod' : IDL.Int,
});
export const DigitalLocker = IDL.Record({
  'unlockDate' : IDL.Opt(IDL.Int),
  'locked' : IDL.Bool,
  'conditionType' : IDL.Opt(UnlockCondition),
});
export const BudgetAllocation = IDL.Record({
  'savingPct' : IDL.Float64,
  'investingPct' : IDL.Float64,
  'spendingPct' : IDL.Float64,
});
export const SavingsGoal = IDL.Record({
  'name' : IDL.Text,
  'locked' : IDL.Bool,
  'deadline' : IDL.Int,
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
});
export const IncomeSource = IDL.Record({
  'name' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Profile = IDL.Record({
  'expenses' : IDL.Vec(Expense),
  'digitalLocker' : DigitalLocker,
  'userProfile' : UserProfile,
  'allocation' : BudgetAllocation,
  'savingsGoals' : IDL.Vec(SavingsGoal),
  'incomeSources' : IDL.Vec(IncomeSource),
});
export const WalletProfile = IDL.Record({
  'balance' : IDL.Nat,
  'kycStatus' : KycStatus,
  'hasPin' : IDL.Bool,
});
export const TransactionType = IDL.Variant({
  'lockerTransfer' : IDL.Null,
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'transactionLabel' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
  'addFundsToWallet' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addIncome' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addSavingsGoal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWallet' : IDL.Func([], [], []),
  'deductFromWallet' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllWalletSummaries' : IDL.Func(
      [],
      [IDL.Vec(WalletSummary), SystemStats],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getInvestmentSuggestions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getKYCStatus' : IDL.Func([], [KycStatus], ['query']),
  'getLockerStatus' : IDL.Func([], [DigitalLocker], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletProfile' : IDL.Func([], [WalletProfile], ['query']),
  'getWalletTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestUnlock' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAllocationSplit' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setWalletPIN' : IDL.Func([IDL.Text], [], []),
  'submitBasicKYC' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitFullKYC' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transferToLockerFromWallet' : IDL.Func([IDL.Nat], [], []),
  'updateSavingsGoal' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'verifyWalletPIN' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const KycStatus = IDL.Variant({
    'full' : IDL.Null,
    'none' : IDL.Null,
    'basic' : IDL.Null,
  });
  const WalletSummary = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
    'kycStatus' : KycStatus,
    'transactionCount' : IDL.Nat,
  });
  const SystemStats = IDL.Record({
    'fullKycCount' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalBalance' : IDL.Nat,
    'basicKycCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const Expense = IDL.Record({
    'date' : IDL.Int,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UnlockCondition = IDL.Variant({
    'goalMet' : IDL.Nat,
    'timePeriod' : IDL.Int,
  });
  const DigitalLocker = IDL.Record({
    'unlockDate' : IDL.Opt(IDL.Int),
    'locked' : IDL.Bool,
    'conditionType' : IDL.Opt(UnlockCondition),
  });
  const BudgetAllocation = IDL.Record({
    'savingPct' : IDL.Float64,
    'investingPct' : IDL.Float64,
    'spendingPct' : IDL.Float64,
  });
  const SavingsGoal = IDL.Record({
    'name' : IDL.Text,
    'locked' : IDL.Bool,
    'deadline' : IDL.Int,
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
  });
  const IncomeSource = IDL.Record({
    'name' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Profile = IDL.Record({
    'expenses' : IDL.Vec(Expense),
    'digitalLocker' : DigitalLocker,
    'userProfile' : UserProfile,
    'allocation' : BudgetAllocation,
    'savingsGoals' : IDL.Vec(SavingsGoal),
    'incomeSources' : IDL.Vec(IncomeSource),
  });
  const WalletProfile = IDL.Record({
    'balance' : IDL.Nat,
    'kycStatus' : KycStatus,
    'hasPin' : IDL.Bool,
  });
  const TransactionType = IDL.Variant({
    'lockerTransfer' : IDL.Null,
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'transactionLabel' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
    'addFundsToWallet' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addIncome' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addSavingsGoal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWallet' : IDL.Func([], [], []),
    'deductFromWallet' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllWalletSummaries' : IDL.Func(
        [],
        [IDL.Vec(WalletSummary), SystemStats],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getInvestmentSuggestions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getKYCStatus' : IDL.Func([], [KycStatus], ['query']),
    'getLockerStatus' : IDL.Func([], [DigitalLocker], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletProfile' : IDL.Func([], [WalletProfile], ['query']),
    'getWalletTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestUnlock' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAllocationSplit' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setWalletPIN' : IDL.Func([IDL.Text], [], []),
    'submitBasicKYC' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitFullKYC' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transferToLockerFromWallet' : IDL.Func([IDL.Nat], [], []),
    'updateSavingsGoal' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'verifyWalletPIN' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };